#!/bin/bash
# Create Git Worktree with Port Allocation
#
# This script creates a new git worktree with automatically allocated
# ports for development servers (web, API, etc.).
#
# Usage: ./create-worktree.sh <feature-name> [project-name]
#
# Example:
#   ./create-worktree.sh auth myproject
#   Creates: ~/Code/myproject-auth with allocated ports

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
BASE_DIR="${BASE_DIR:-$HOME/Code}"
FEATURE_NAME="${1:-}"
PROJECT_NAME="${2:-}"

# Port ranges
WEB_PORT_BASE=8001
API_PORT_BASE=9001
PORT_RANGE=99

# Helper functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Calculate ports based on branch name hash
allocate_ports() {
    local name="$1"
    local hash_val=0

    # Sum character values
    for (( i=0; i<${#name}; i++ )); do
        char="${name:$i:1}"
        val=$(printf '%d' "'$char")
        hash_val=$((hash_val + val))
    done

    # Allocate ports
    local web_port=$((WEB_PORT_BASE + (hash_val % PORT_RANGE)))
    local api_port=$((API_PORT_BASE + (hash_val % PORT_RANGE)))

    echo "$web_port $api_port"
}

# Validate input
if [[ -z "$FEATURE_NAME" ]]; then
    log_error "Feature name required."
    echo ""
    echo "Usage: $0 <feature-name> [project-name]"
    echo ""
    echo "Examples:"
    echo "  $0 auth myproject"
    echo "  $0 feature-authentication"
    echo ""
    exit 1
fi

# If no project specified, try to detect from git
if [[ -z "$PROJECT_NAME" ]]; then
    # Check if we're in a git repo
    if git rev-parse --show-toplevel &> /dev/null; then
        PROJECT_NAME=$(basename "$(git rev-parse --show-toplevel)")
        log_info "Detected project: $PROJECT_NAME"
    else
        log_error "Could not detect project name."
        log_info "Provide project name as second argument:"
        echo "  $0 $FEATURE_NAME myproject"
        exit 1
    fi
fi

# Paths
MAIN_PATH="$BASE_DIR/$PROJECT_NAME"
WORKTREE_PATH="$BASE_DIR/${PROJECT_NAME}-${FEATURE_NAME}"

# Check if main project exists
if [[ ! -d "$MAIN_PATH" ]]; then
    log_error "Main project not found: $MAIN_PATH"
    exit 1
fi

# Check if it's a git repo
if [[ ! -d "$MAIN_PATH/.git" ]]; then
    log_error "Not a git repository: $MAIN_PATH"
    exit 1
fi

# Check if worktree already exists
if [[ -d "$WORKTREE_PATH" ]]; then
    log_warning "Worktree path already exists: $WORKTREE_PATH"
    read -p "Continue and reconfigure? (y/N): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        log_info "Cancelled."
        exit 0
    fi
else
    # Create the worktree
    log_info "Creating worktree: $WORKTREE_PATH"

    BRANCH_NAME="feature/$FEATURE_NAME"

    # Check if branch already exists
    if git -C "$MAIN_PATH" branch --list "$BRANCH_NAME" | grep -q .; then
        log_info "Branch $BRANCH_NAME already exists. Using existing branch."
        git -C "$MAIN_PATH" worktree add "$WORKTREE_PATH" "$BRANCH_NAME"
    else
        git -C "$MAIN_PATH" worktree add "$WORKTREE_PATH" -b "$BRANCH_NAME"
    fi

    log_success "Worktree created."
fi

# Allocate ports
log_info "Allocating ports..."
read -r WEB_PORT API_PORT < <(allocate_ports "$FEATURE_NAME")

# Create .env.ports file
ENV_FILE="$WORKTREE_PATH/.env.ports"
cat > "$ENV_FILE" << EOF
# Auto-generated ports for worktree: $FEATURE_NAME
# Generated by: $(basename "$0")
# Date: $(date)

WEB_PORT=$WEB_PORT
API_PORT=$API_PORT

# Use in your application:
# export PORT=\$WEB_PORT
# export API_PORT=\$API_PORT
EOF

log_success "Ports allocated: WEB=$WEB_PORT, API=$API_PORT"

# Display summary
echo ""
echo -e "${GREEN}=================================="
echo "Worktree Created"
echo "==================================${NC}"
echo ""
echo "Location:  $WORKTREE_PATH"
echo "Branch:    feature/$FEATURE_NAME"
echo "Ports:     WEB=$WEB_PORT, API=$API_PORT"
echo ""
echo "Environment file created: .env.ports"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo "1. Navigate to worktree:"
echo "   cd $WORKTREE_PATH"
echo ""
echo "2. Source the ports (or use in your app):"
echo "   source .env.ports"
echo ""
echo "3. Start your dev server with allocated ports"
echo ""
echo "4. Create a tmux window for this worktree:"
echo "   C-a c          # Create new window"
echo "   C-a ,          # Rename to '$FEATURE_NAME'"
echo ""
